apiVersion: v1
kind: ConfigMap
metadata:
  name: redisinsight-config
data:
  connections.json: |
    {
      "connections": [
        {
          "id": "default-redis",
          "name": "Redis - Default",
          "host": "redis",
          "port": 6379,
          "db": 0,
          "description": "Default Redis Cache for Nexlura System"
        }
      ]
    }
