apiVersion: v1
kind: Namespace
metadata:
  name: postgres-dev
  labels:
    name: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgres-dev
  labels:
    app: postgres
data:
  POSTGRES_DB: propati
  POSTGRES_USER: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-dev
type: Opaque
stringData:
  POSTGRES_PASSWORD: admin
  POSTGRES_REPLICATION_PASSWORD: admin
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: postgres-dev
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: postgres-dev
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: "/mnt/volumes/pgsql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgres
  namespace: postgres-dev
spec:
  replicas: 3
  image: postgres:15
  database:
    size: 30Gi
    storageClassName: standard
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_REPLICATION_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-dev
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432